### ISSUE TITLE
Problem maybe in call to wait.py

### ISSUE THREAD

**Issue by StrangeDOS** [shibi391/read_comic_offline#2]
Here is the output I had.

Choose browser mode (head/headless): headless
Choose quality of the comic (high/low): high
Do you want to delete images after they get converted to cbr (yes/no): no
Paste the url of the comic: https://readcomiconline.to/Comic/Untold-Tales-Of-The-New-Universe-D-P-7
[WDM] - Driver [C:\Users\<removed>\.wdm\drivers\geckodriver\win64\v0.27.0\geckodriver.exe] found in cache
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    quality = Select(WebDriverWait(browser, timeout).until(EC.presence_of_element_located((By.ID, "selectQuality"))))
  File "C:\Users\<removed>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

Not sure what the problem is here. Thanks for your time. :)

**Comment by iShibi** [comment]
The problem is in the URL. The correct URL for the comic you want to download is this: https://readcomiconline.to/Comic/Untold-Tales-Of-The-New-Universe-D-P-7/Full?id=157330
The URL you entered is of the page where the comic is listed, to get the correct URL, always open the comic first and then copy the URL of that page. I'm working on a search mode, which will let you download a comic without any URL. Until then keep tinkering with this version. Also, thank you for checking out my project, your issues help me in refining this thing. ;-)

**Comment by StrangeDOS** [comment]
My pleasure to help.  And yes, using the correct URL did work as far as getting the images downloaded and compressed into a .cbr file.  Unfortunately the file isn't formatted correctly.  I think I understand what happened.  Instead of creating a .RAR file and copying the .JPGs into it, it is coping the entire path.  So instead of the .JPGs being just inside the .RAR file, they are under serveral nested directories within the .RAR (in my case users\<removed>\downloads\read_comic_offline_master).  So after the file is renamed to .CBR, the comic reader can't find the .JPGs.

**Comment by iShibi** [comment]
Hey, can you post the screenshots of the problem you are facing? It would give me some more insight into the issue. Also, do you have any comic reader installed which can read a .cbr file? If you don't have one, you can download the one I use from here: https://www.cdisplayex.com/

**Comment by StrangeDOS** [comment]
I'm using Comicana.  But itsn't not the only one I've got.  Tomorrow I'll get the screenshot for you and also try it in other readers too.

**Comment by iShibi** [comment]
Okay. Btw, I have fixed the problems you have raised in the other two issues. Check the updates and if they work, you can close that issue.
